# Generated by Django 2.2.3 on 2019-07-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('uid', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=64)),
                ('tokens', models.TextField()),
                ('email', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField()),
                ('last_time', models.DateTimeField()),
            ],
        ),
    ]
