# Generated by Django 2.2.3 on 2019-07-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190715_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='extras',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.TextField(default='', null=True),
        ),
    ]
