# Generated by Django 2.2.3 on 2019-07-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190715_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='access_uid',
        ),
    ]
