# Generated by Django 2.2.3 on 2019-07-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_useractivity_access_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='content',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
