# Generated by Django 2.2.3 on 2019-07-15 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userlog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='access_time',
            field=models.DateTimeField(),
        ),
    ]
